application: <YOUR_APPLICATION_ID_HERE>
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /rw_common
  static_dir: resources/rw_common

- url: /strategy/.*
  script: pages/strategy.py
  login: admin

- url: /chanchero/mastertask
  script: chanchero/mastertaskhandler.py
  login: admin

- url: /chanchero/workertask
  script: chanchero/workertaskhandler.py
  login: admin

- url: /chanchero/resulttask
  script: chanchero/resulttaskhandler.py
  login: admin

- url: /.*
  script: pages/home.py
  login: admin

libraries:
- name: numpy
  version: "latest"
