#stock_list="A  AA  AAPL  ABC  ABT  ACE  ACN  ACT  ADBE  ADI  ADM  ADP  ADS  ADSK  AEE  AEP  AES  AET  AFL  AGN  AIG  AIV  AIZ  AKAM  ALL  ALTR  ALXN  AMAT  AME  AMGN  AMP  AMT  AMZN  AN  AON  APA  APC  APD  APH  ARG  ATI  AVB  AVP  AVY  AXP  AZO  BA  BAC  BAX  BBBY  BBT  BBY  BCR  BDX  BEAM  BEN  BF-B  BHI  BIIB  BK  BLK  BLL  BMS  BMY  BRCM  BRK-B  BSX  BTU   BXP  C  CA  CAG  CAH  CAM  CAT  CB  CBG  CBS  CCE  CCI  CCL  CELG  CERN  CF  CFN  CHK  CHRW  CI  CINF  CL  CLF  CLX  CMA  CMCSA  CME  CMG  CMI  CMS  CNP  CNX  COF  COG  COH  COL  COP  COST  COV  CPB  CRM  CSC  CSCO  CSX  CTAS  CTL  CTSH  CTXS  CVC  CVS  CVX  D  DAL  DD  DE  DFS  DG  DGX  DHI  DHR  DIS  DISCA   DLTR  DNB  DNR  DO  DOV  DOW  DPS  DRI  DTE  DTV  DUK  DVA  DVN  EA  EBAY  ECL  ED  EFX  EIX  EL  EMC  EMN  EMR  EOG  EQR  EQT  ESRX  ESV  ETFC  ETN  ETR  EW  EXC  EXPD  EXPE  F  FAST  FCX  FDO  FDX  FE  FFIV  FIS  FISV  FITB  FLIR  FLR  FLS  FMC  FOSL  FOXA  FRX  FSLR  FTI  FTR  GAS  GCI  GD  GE   GHC  GILD  GIS  GLW   GME  GNW  GOOG  GPC  GPS  GRMN  GS  GT  GWW  HAL  HAR  HAS  HBAN  HCBK  HCN  HCP  HD  HES  HIG  HOG  HON  HOT  HP  HPQ  HRB  HRL  HRS  HSP  HST  HSY  HUM  IBM  ICE  IFF  IGT  INTC  INTU  IP  IPG  IR  IRM  ISRG  ITW  IVZ  JBL  JCI  JEC  JNJ  JNPR  JOY  JPM  JWN  K  KEY   TWX  TXN  TXT  TYC  UNH  UNM  UNP  UPS  URBN  USB  UTX  V  VAR  VFC  VIAB  VLO  VMC  VNO  VRSN  VRTX  VTR  VZ  WAG  WAT  WDC  WEC  WFC  WFM  WHR  WIN  WLP  WM  WMB  WMT  WU  WY  WYN  WYNN  X  XEL  XL  XLNX  XOM  XRAY  XRX  YHOO  YUM  ZION  ZMH"
#for s in $stock_list;do
#wget http://ichart.yahoo.com/table.csv\?s=$s
#mv table.csv?s=$s $s
#
for j in `ls data`; do
python rsi_analysis.py data/$j >> result_sample
done
#python rsi_analysis.py $s

#done
